#!/bin/bash
# Fix volume ownership when mount is root-owned (e.g. Coolify / host bind mount).
# Then run the real entry script as the steam user.
set -e
STEAMAPPDIR="${STEAMAPPDIR:-/home/steam/csgo-dedicated}"
if [ -d "$STEAMAPPDIR" ] && [ -w "/" ]; then
  chown -R steam:steam "$STEAMAPPDIR" 2>/dev/null || true
fi
# Pass through env vars required by entry.sh (runuser may not inherit)
exec runuser -u steam -- env \
  HOMEDIR="${HOMEDIR}" \
  STEAMAPPDIR="${STEAMAPPDIR}" \
  STEAMAPP="${STEAMAPP}" \
  STEAMAPPID="${STEAMAPPID}" \
  STEAMCMDDIR="${STEAMCMDDIR}" \
  SRCDS_PORT="${SRCDS_PORT}" \
  SRCDS_TV_PORT="${SRCDS_TV_PORT}" \
  SRCDS_CLIENT_PORT="${SRCDS_CLIENT_PORT}" \
  SRCDS_TOKEN="${SRCDS_TOKEN}" \
  SRCDS_FPSMAX="${SRCDS_FPSMAX}" \
  SRCDS_TICKRATE="${SRCDS_TICKRATE}" \
  SRCDS_MAXPLAYERS="${SRCDS_MAXPLAYERS}" \
  SRCDS_NET_PUBLIC_ADDRESS="${SRCDS_NET_PUBLIC_ADDRESS}" \
  SRCDS_IP="${SRCDS_IP}" \
  SRCDS_LAN="${SRCDS_LAN}" \
  SRCDS_RCONPW="${SRCDS_RCONPW}" \
  SRCDS_PW="${SRCDS_PW}" \
  SRCDS_HOSTNAME="${SRCDS_HOSTNAME}" \
  SRCDS_STARTMAP="${SRCDS_STARTMAP}" \
  SRCDS_REGION="${SRCDS_REGION}" \
  SRCDS_MAPGROUP="${SRCDS_MAPGROUP}" \
  SRCDS_GAMETYPE="${SRCDS_GAMETYPE}" \
  SRCDS_GAMEMODE="${SRCDS_GAMEMODE}" \
  SRCDS_HOST_WORKSHOP_COLLECTION="${SRCDS_HOST_WORKSHOP_COLLECTION}" \
  SRCDS_WORKSHOP_START_MAP="${SRCDS_WORKSHOP_START_MAP}" \
  SRCDS_WORKSHOP_AUTHKEY="${SRCDS_WORKSHOP_AUTHKEY}" \
  METAMOD_VERSION="${METAMOD_VERSION}" \
  SOURCEMOD_VERSION="${SOURCEMOD_VERSION}" \
  SCRIM="${SCRIM}" \
  bash "${HOMEDIR}/entry.sh"
